# Generated by Django 6.0.7 on 2026-07-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discogs_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="formato",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="sello",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="tracklist",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="imagen",
            field=models.ImageField(blank=True, upload_to="productos/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
